/*
 http://www.gnu.org/licenses/gpl.html GNU General Public License, version 3 or later
*/
var SvpStarter=function(d){function f(a){console.log("SVPS | "+a)}function G(){var a=d("."+g.container);if(l.topic)p.topic=d(".topics .topic",a).not(".template").length;if(l.speaker)p.speaker=d(".speakers .speaker",a).not(".template").length}function H(){if(y>0)if(typeof SvpPolling!=="undefined"){var a=y*1E3,b=d("#"+g.data).attr("data-hash");c.player.onPlay(function(){SvpPolling.init(b,I,a)});c.player.onPause(function(){SvpPolling.stop();m("speaker");m("topic")})}else f(h.no_svpp,true);else f(h.svpp_off,
false)}function z(a,b){a=a[a.length-1].id;q[b]!==a&&v(a,b)}function A(a,b){var i=d("."+g.container+" ."+b+"s ."+b).last(),n=i.parent();if(i.hasClass("template")){i.removeClass("template");i.remove();n.removeClass("template")}for(var j=0;j<a.length;j++){var k=i.clone(),r=a[j];switch(b){case "speaker":d(".speaker-avatar",k).attr("src",J+r.photo);d(".speaker-data",k).html(r.firstname+" "+r.lastname);break;case "topic":d(".topic-title",k).html(r.title);d(".topic-description",k).html(r.description)}k.attr("data-"+
b,r.id).removeClass("active");n.append(k);p[b].length++}}function K(a){for(var b in a)if(a.hasOwnProperty(b))s.playlist[a[b].streamfileId]=parseInt(b,10)}function L(){var a=null;if(l.topic){d("."+g.container+" .topics").on("click",".topic .topic-link",function(j){j.preventDefault();c.jumpToTopic(d(this).parent(".topic").attr("data-topic"))});var b=d("#"+g.topicTimeline).first();if(b.exists()){try{a=JSON.parse(b.html())}catch(i){f(h.no_json_support,true);return false}a.length>0&&B("topic",a,true);
b.html("")}f(h.events_topic_init,false)}if(l.speaker){b=d("#"+g.speakerTimeline).first();if(b.exists()){a=null;try{a=JSON.parse(b.html())}catch(n){f(h.no_json_support,true);return false}a.length>0&&B("speaker",a,false);b.html("")}f(h.events_speaker_init,false)}}function B(a,b,i){for(var n=0;n<b.length;n++){var j=b[n],k=n+1;j.start=Math.floor(j.relativeTime/1E3);j.end=k<b.length&&j.streamfileId===b[k].streamfileId?Math.floor(b[k].relativeTime/1E3):Number.MAX_SAFE_INTEGER;if(i)s[a][j.id]={playlist:s.playlist[j.streamfileId],
time:j.start};c.player.onTime(w.onTime(j,a));c.player.onSeek(w.onSeek(j,a))}c.player.onSeek(w.onSeekFinal(a))}function u(){c.jw=jwplayer(g.player);c.jw.onReady(function(){m("speaker");m("topic");M()})}function M(){var a=null;for(a in e.onTime)e.onTime.hasOwnProperty(a)&&c.jw.onTime(e.onTime[a]);for(a in e.onSeek)e.onSeek.hasOwnProperty(a)&&c.jw.onSeek(e.onSeek[a]);for(a in e.onPlay)e.onPlay.hasOwnProperty(a)&&c.jw.onPlay(e.onPlay[a]);for(a in e.onPause)e.onPause.hasOwnProperty(a)&&c.jw.onPause(e.onPause[a]);
f(h.events_re,false)}function m(a){if(l[a]){d("."+g.container+" ."+a+"s ."+a+".active").removeClass("active");q[a]=0}}function v(a,b){m(b);d("."+g.container+" ."+b+"s ."+b+"[data-"+b+"="+a+"]").first().addClass("active");q[b]=a;f(h.activate+" "+b+" "+a,false)}function C(a,b){c.player.playlistNext();a++;a<b&&c.jw.onReady(function(){setTimeout(function(){C(a,b)},50)})}function D(a,b){c.player.playlistPrev();a--;a>b&&c.jw.onReady(function(){setTimeout(function(){D(a,b)},50)})}function N(a){t.hasOwnProperty(a.playlist)||
(t[a.playlist]={});t[a.playlist][a.time]=true;c.jw.onPlay(function(){if(t[a.playlist][a.time]){c.player.seek(a.time);t[a.playlist][a.time]=false}})}function E(a){return s.playlist[a.streamfileId]===c.player.getPlaylistIndex()}function F(){if(typeof jwplayer==="undefined"){f(h.no_jwplayer,true);return false}jwplayer.key="###JWPLAYER_KEY###";return true}function O(a){if(F(true)){if(typeof smvplayer!=="undefined"){c.player=smvplayer(g.player);c.player.init(a);c.jw=jwplayer(g.player);c.player.onTime=
function(b){e.onTime.push(b);c.jw.onTime(b)};c.player.onSeek=function(b){e.onSeek.push(b);c.jw.onSeek(b)};c.player.onPlay=function(b){e.onPlay.push(b);c.jw.onPlay(b)};c.player.onPause=function(b){e.onPause.push(b);c.jw.onPause(b)};o.player.next=c.player.next;c.player.next=function(){o.player.next();u()};o.player.previous=c.player.previous;c.player.previous=function(){o.player.previous();u()};o.player.setQualityLevel=c.player.setQualityLevel;c.player.setQualityLevel=function(b){o.player.setQualityLevel(b);
u()};o.player.setAudioLanguage=c.player.setAudioLanguage;c.player.setAudioLanguage=function(b){o.player.setAudioLanguage(b);u()};c.player.getPlaylistIndex=function(){return c.player.getTimeline().currentItem};c.player.playlistNext=function(){c.player.next()};c.player.playlistPrev=function(){c.player.previous()};c.player.playlistItem=function(b){b=b-c.player.getPlaylistIndex();if(b>0)C(0,b);else b<0&&D(0,b)};return true}f(h.no_smvplayer,true)}return false}function P(a){if(F(false)){jwplayer(g.player).setup(a);
c.player=jwplayer(g.player);c.jw=c.player;c.player.onPlaylistItem(function(){m("speaker");m("topic")});return true}return false}var J="###SPEAKER_IMAGE_DIR###",y=parseInt("###POLLING_INTERVAL###",10),I=parseInt("###CURRENT_PAGE_ID###",10),Q=parseInt("###PLAYER_TYPE###",10),l={topic:parseInt("###MEETINGDATA_TOPICS###",10),speaker:parseInt("###MEETINGDATA_SPEAKERS###",10)},s={playlist:{},topic:{}},p={topic:0,speaker:0},q={topic:0,speaker:0},o={player:{next:null,previous:null,setQualityLevel:null,setAudioLanguage:null}},
e={onTime:[],onSeek:[],onPlay:[],onPause:[]},t={},x={topic:false,speaker:false},w={onTime:function(a,b){return function(i){i.position>=a.start&&i.position<a.start+0.4&&a.id!==q[b]&&E(a)&&v(a.id,b)}},onSeek:function(a,b){return function(i){if(i.offset>=a.start&&i.offset<a.end&&E(a)){a.id!==q[b]&&v(a.id,b);x[b]=true}}},onSeekFinal:function(a){return function(){!x[a]&&q[a]!==0&&m(a);x[a]=false}}},g={player:"tx-streamovations-vp-play",data:"tx-streamovations-vp-playerdata",topicTimeline:"tx-streamovations-vp-topictimeline",
speakerTimeline:"tx-streamovations-vp-speakertimeline",container:"tx-streamovations-vp"},h={no_svpp:"SVPP not loaded, polling inactive",svpp_off:"Polling disabled",no_player_data:"The player element or player data is not available",no_json_support:"No JSON.parse support in user agent",player_data_invalid:"Player data is invalid or in an unsupported format",invalid_player:"No supported player configured",no_jwplayer:"No jwplayer loaded",no_jwplayer_key:"A jwplayer license key is required",no_smvplayer:"No smvplayer loaded",
events_topic_init:"initializing topic event handlers",events_speaker_init:"initializing speaker event handlers",events_re:"Reattached event callbacks",no_timestamp:"Topic has no registered timestamps",activate:"Activated"};d.fn.exists=function(){return this.length!==0};var c={player:null,jw:null,isLiveStream:false,init:function(){var a=d("#"+g.player),b=d("#"+g.data).first();if(!a.exists()||!b.exists()){f(h.no_player_data,true);return false}a=null;try{a=JSON.parse(b.html().trim())}catch(i){f(h.no_json_support,
true);return false}b.html("");if(typeof a!=="object"){f(h.player_data_invalid,true);return false}switch(Q){case 2:if(!O(a))return false;break;case 1:if(!P(a))return false;break;default:f(h.invalid_player,true);return false}a.hasOwnProperty("playlist")&&K(a.playlist);if(a.hasOwnProperty("application"))this.isLiveStream=a.application==="rtplive";if(this.isLiveStream){if(l.topic||l.speaker){G();H()}}else L();return true},processMeetingdataChange:function(a){if(l.topic){a.hasOwnProperty("topics")&&a.topics!==
false&&a.topics.length>p.topic&&A(a.topics.slice(p.topic),"topic");a.hasOwnProperty("topicTimeline")&&a.topicTimeline!==false&&a.topicTimeline.length>0&&z(a.topicTimeline,"topic")}if(l.speaker){a.hasOwnProperty("speakers")&&a.speakers!==false&&a.speakers.length>p.speaker&&A(a.speakers.slice(p.speaker),"speaker");a.hasOwnProperty("speakerTimeline")&&a.speakerTimeline!==false&&a.speakerTimeline.length>0&&z(a.speakerTimeline,"speaker")}},jumpToTopic:function(a){a=s.topic[a];if(a!==undefined){a.playlist!==
this.player.getPlaylistIndex()&&this.player.playlistItem(a.playlist);if(this.jw.getState()!=="PLAYING"){N(a);this.jw.play(true)}else this.player.seek(a.time)}else f(h.no_timestamp,true)}};return c}(jQuery);