/*
 http://www.gnu.org/licenses/gpl.html GNU General Public License, version 3 or later
*/
var SvpStarter=function(g){function i(a){console.log("SVPS | "+a)}function K(){var a=g("."+e.container);if(l.topic)r.topic=g(".topics .topic",a).not(".template").length;if(l.speaker)r.speaker=g(".speakers .speaker",a).not(".template").length}function B(a){if(L>0)if(typeof SvpPolling!=="undefined"){var b=L*1E3,c=g("#"+e.data).attr("data-hash");if(a)SvpPolling.init(c,M,b);else{s(function(){SvpPolling.init(c,M,b)});y(function(){SvpPolling.stop();m("speaker");m("topic")})}}else i(h.no_svpp,true);else i(h.svpp_off,
false)}function U(a){a=a[a.length-1];try{if(a.valid){var b=Math.round((new Date).getTime()/1E3);if(n.eventBreak)a.end!==null&&a.utcEnd<=b&&V();else if(a.utc<=b)if(a.end===null||a.utcEnd>b)W()}}catch(c){i(h.invalid_eventbreak,true)}}function V(){SvpPolling.stop();var a=g("."+e.container+" .video-player-break"),b='<div id="'+e.player+'" class="video-player"></div>';a.parent().append(b);a.remove();n.eventBreak=false;d.init();C()}function W(){D();f={onTime:[],onSeek:[],onPlay:[],onPause:[]};var a=g("."+
e.container+" #"+e.playerPI).first(),b='<div class="video-player-break"><div class="text"><div class="title">'+h.video_break_title+'</div><div class="sub">'+h.video_break_sub+"</div></div></div>";a.parent().append(b);a.remove();n.eventBreak=true;B(true)}function N(a,b){a=a[a.length-1].id;n[b]!==a&&E(a,b)}function O(a,b){var c=g("."+e.container+" ."+b+"s ."+b).last(),k=c.parent();if(c.hasClass("template")){c.removeClass("template");c.remove();k.removeClass("template")}for(var j=0;j<a.length;j++){var o=
c.clone(),t=a[j];switch(b){case "speaker":g(".speaker-avatar",o).attr("src",X+t.photo);g(".speaker-data",o).html(t.firstname+" "+t.lastname);break;case "topic":g(".topic-title",o).html(t.title);g(".topic-description",o).html(t.description)}o.attr("data-"+b,t.id).removeClass("active");k.append(o);r[b].length++}}function Y(a){var b={};for(var c in a)if(a.hasOwnProperty(c))b[a[c].streamfileId]=parseInt(c,10);return b}function Z(){var a=null;if(l.topic){g("."+e.container+" .topics").on("click",".topic .topic-link",
function(j){j.preventDefault();d.jumpToTopic(g(this).parent(".topic").attr("data-topic"))});var b=g("#"+e.topicTimeline).first();if(b.exists()){try{a=JSON.parse(b.html())}catch(c){i(h.no_json_support,true);return false}a.length>0&&P("topic",a,true);b.html("")}i(h.events_topic_init,false)}if(l.speaker){b=g("#"+e.speakerTimeline).first();if(b.exists()){a=null;try{a=JSON.parse(b.html())}catch(k){i(h.no_json_support,true);return false}a.length>0&&P("speaker",a,false);b.html("")}i(h.events_speaker_init,
false)}}function P(a,b,c){for(var k=0;k<b.length;k++){var j=b[k],o=k+1;j.start=Math.floor(j.relativeTime/1E3);j.end=o<b.length&&j.streamfileId===b[o].streamfileId?Math.floor(b[o].relativeTime/1E3):Number.MAX_SAFE_INTEGER;j.playlist=F(j);if(c)Q[a][j.id]={playlist:j.playlist,time:j.start};z(G.onTime(j,a));u(G.onSeek(j,a))}u(G.onSeekFinal(a))}function R(a,b){m("speaker");m("topic");v(a,b);S()}function w(){d.jw=jwplayer(e.playerObj);d.jw.onReady(function(){m("speaker");m("topic");$()})}function $(){var a=
null;for(a in f.onTime)f.onTime.hasOwnProperty(a)&&d.jw.onTime(f.onTime[a]);for(a in f.onSeek)f.onSeek.hasOwnProperty(a)&&d.smv.onSeek(f.onSeek[a]);S()}function S(){var a=null;for(a in f.onPlay)f.onPlay.hasOwnProperty(a)&&d.smv.onPlay(f.onPlay[a]);for(a in f.onPause)f.onPause.hasOwnProperty(a)&&d.smv.onPause(f.onPause[a]);i(h.events_re,false)}function m(a){if(l[a]){var b=g("."+e.container+" ."+a+"s");g("."+a+".active",b).removeClass("active");n[a]=0;b.trigger("SVPS:inactive-"+a)}}function E(a,b){var c=
g("."+e.container+" ."+b+"s"),k=g("."+b+"[data-"+b+"="+a+"]",c);g("."+b+".active",c).removeClass("active");n[b]=a;k.first().addClass("active");c.trigger("SVPS:active-"+b,{id:a,index:k.index()});i(h.activate+" "+b+" "+a,false)}function v(a,b){x.hasOwnProperty(b)||(x[b]={});x[b][a]=true;s(function(){if(x[b][a]){q(a,b);x[b][a]=false}})}function H(){if(typeof jwplayer==="undefined"){i(h.no_jwplayer,true);return false}jwplayer.key="###JWPLAYER_KEY###";return true}function aa(a){if(H(false)){if(typeof smvplayer!==
"undefined"){d.smv=smvplayer(e.player);d.smv.init(a);p=function(){return d.smv.getCurrentPlaylistItem().streamfileId};F=function(b){return b.streamfileId};C=function(){d.smv.whenReady(function(){d.smv.play()})};D=function(){d.smv.stop()};a=d.smv.getEngine();if(a==="jw")ba();else a==="html5"&&ca();e.playerPI=e.smvWrapper1+e.player;return true}i(h.no_smvplayer,true)}return false}function ba(){d.player=d.smv;e.playerObj=e.smvWrapper1+e.smvWrapper2+e.player;d.jw=jwplayer(e.playerObj);z=function(b){f.onTime.push(b);
d.jw.onTime(b)};u=function(b){f.onSeek.push(b);d.smv.onSeek(b)};s=function(b){f.onPlay.push(b);d.smv.onPlay(b)};y=function(b){f.onPause.push(b);d.smv.onPause(b)};var a={};a.next=d.smv.next;d.smv.next=function(){a.next();w()};a.previous=d.smv.previous;d.smv.previous=function(){a.previous();w()};a.setQualityLevel=d.smv.setQualityLevel;d.smv.setQualityLevel=function(b){a.setQualityLevel(b);w()};a.setAudioLanguage=d.smv.setAudioLanguage;d.smv.setAudioLanguage=function(b){a.setAudioLanguage(b);w()};A=
function(b){var c=d.smv.getStatus();if(c!=="PLAYING"&&c!=="IDLE"){v(b.time,b.playlist);d.smv.play()}else q(b.time,b.playlist)};q=function(b,c){if(c===p())c=null;d.smv.seek(b,c);c!==null&&w()}}function ca(){e.playerObj=e.player+e.html5Wrapper;d.player=document.getElementById(e.playerObj);d.player.addEventListener("timeupdate",function(){for(var b in f.onTime)f.onTime.hasOwnProperty(b)&&f.onTime[b]({position:this.currentTime})});d.player.addEventListener("seeking",function(){i("Seeking event fired: time "+
this.currentTime);for(var b in f.onSeek)f.onSeek.hasOwnProperty(b)&&f.onSeek[b]({offset:this.currentTime})});z=function(b){f.onTime.push(b)};u=function(b){f.onSeek.push(b)};s=function(b){f.onPlay.push(b);d.smv.onPlay(b)};y=function(b){f.onPause.push(b);d.smv.onPause(b)};var a={};a.setQualityLevel=d.smv.setQualityLevel;d.smv.setQualityLevel=function(b){var c=d.player.currentTime,k=p();a.setQualityLevel(b);R(c,k)};a.setAudioLanguage=d.smv.setAudioLanguage;d.smv.setAudioLanguage=function(b){var c=d.player.currentTime,
k=p();a.setAudioLanguage(b);R(c,k)};d.smv.onComplete(function(){m("speaker");m("topic")});A=function(b){var c=b.playlist===p()?null:b.playlist;if(d.smv.getStatus()==="PLAYING")q(b.time,c);else if(c===null){v(b.time,null);d.smv.play()}else i(h.no_playlist_seek,true)};q=function(b,c){d.smv.seek(b,c)}}function T(a){jwplayer(e.player).setup(a);d.jw=jwplayer(e.player);d.player=d.jw;z=function(c){d.jw.onTime(c)};u=function(c){d.jw.onSeek(c)};s=function(c){d.jw.onPlay(c)};y=function(c){d.jw.onPause(c)};
p=function(){return d.jw.getPlaylistIndex()};C=function(){d.jw.onReady(function(){d.jw.play()})};D=function(){d.jw.stop()};d.jw.onPlaylistItem(function(){m("speaker");m("topic")});A=function(c){if(d.jw.getState().toUpperCase()!=="PLAYING"){v(c.time,c.playlist);d.jw.play()}else q(c.time,c.playlist)};if(a.hasOwnProperty("playlist")){var b=Y(a.playlist);F=function(c){return b[c.streamfileId]}}else{i(h.no_playlist,true);l.topic=false;l.speaker=false}}function da(a){if(H(true)){T(a);q=function(b,c){if(p()!==
c){d.jw.once("playlistItem",function(){d.jw.once("play",function(){d.jw.seek(b)})});d.jw.playlistItem(c)}else d.jw.seek(b)};v=function(b,c){d.jw.once("play",function(){q(b,c)})};return true}return false}function ea(a){if(H(false)){T(a);q=function(b,c){if(p()!==c){I[c]=true;d.jw.onPlaylistItem(function(){if(I[c]){d.jw.seek(b);I[c]=false}});d.jw.playlistItem(c)}else d.jw.seek(b)};return true}return false}var X="###SPEAKER_IMAGE_DIR###",L=parseInt("###POLLING_INTERVAL###",10),M=parseInt("###CURRENT_PAGE_ID###",
10),fa=parseInt("###PLAYER_TYPE###",10),l={breaks:parseInt("###MEETINGDATA_BREAKS###",10),topic:parseInt("###MEETINGDATA_TOPICS###",10),speaker:parseInt("###MEETINGDATA_SPEAKERS###",10)},Q={topic:{}},r={topic:0,speaker:0},n={topic:0,speaker:0,eventBreak:false},f={onTime:[],onSeek:[],onPlay:[],onPause:[]},x={},I={},J={topic:false,speaker:false},G={onTime:function(a,b){return function(c){c.position>=a.start&&c.position<a.start+0.4&&a.id!==n[b]&&a.playlist===p()&&E(a.id,b)}},onSeek:function(a,b){return function(c){if(c.offset>=
a.start&&c.offset<a.end&&a.playlist===p()){a.id!==n[b]&&E(a.id,b);J[b]=true}}},onSeekFinal:function(a){return function(){!J[a]&&n[a]!==0&&m(a);J[a]=false}}},e={player:"tx-streamovations-vp-play",playerObj:"tx-streamovations-vp-play",playerPI:"tx-streamovations-vp-play",playerContainer:"video-player-container",smvWrapper1:"smvplayer_",smvWrapper2:"engineWrapper_",html5Wrapper:"_html5videotag",data:"tx-streamovations-vp-playerdata",topicTimeline:"tx-streamovations-vp-topictimeline",speakerTimeline:"tx-streamovations-vp-speakertimeline",
container:"tx-streamovations-vp"},h={no_svpp:"SVPP not loaded, polling inactive",svpp_off:"Polling disabled",no_player_data:"The player element or player data is not available",no_playlist:"Missing essential playlist data",no_json_support:"No JSON.parse support in user agent",player_data_invalid:"Player data is invalid or in an unsupported format",invalid_player:"No supported player configured",invalid_eventbreak:"Eventbreak data is invalid or in an unsupported format",no_jwplayer:"No jwplayer loaded",
no_jwplayer_key:"A jwplayer license key is required",no_smvplayer:"No smvplayer loaded",events_topic_init:"initializing topic event handlers",events_speaker_init:"initializing speaker event handlers",events_re:"Reattached event callbacks",no_timestamp:"Topic has no registered timestamps",no_playlist_seek:"Can only seek to other playlist item during playback",activate:"Activated",video_break_title:"###VIDEO_BREAK_TITLE###",video_break_sub:"###VIDEO_BREAK_SUB###"};g.fn.exists=function(){return this.length!==
0};var u=null,z=null,s=null,y=null,p=null,F=null,A=null,q=null,D=null,C=null,d={player:null,jw:null,smv:null,isLiveStream:false,init:function(){var a=g("."+e.playerContainer),b=g("#"+e.data).first();if(!a.exists()||!b.exists()){i(h.no_player_data,true);return false}var c=null;try{c=JSON.parse(b.html().trim())}catch(k){i(h.no_json_support,true);return false}if(typeof c!=="object"){i(h.player_data_invalid,true);return false}if(c.hasOwnProperty("application"))this.isLiveStream=c.application==="rtplive";
if(g("#"+e.player,a).exists()){switch(fa){case 3:if(!aa(c))return false;break;case 2:if(!da(c))return false;break;case 1:if(!ea(c))return false;break;default:i(h.invalid_player,true);return false}s(function(){a.trigger("SVPS:play")});if(this.isLiveStream){if(l.topic||l.speaker||l.breaks){K();B(false)}}else Z()}else if(this.isLiveStream&&l.breaks){n.eventBreak=true;K();B(true)}return true},processMeetingdataChange:function(a){if(l.topic){a.hasOwnProperty("topics")&&a.topics!==false&&a.topics.length>
r.topic&&O(a.topics.slice(r.topic),"topic");a.hasOwnProperty("topicTimeline")&&a.topicTimeline!==false&&a.topicTimeline.length>0&&N(a.topicTimeline,"topic")}if(l.speaker){a.hasOwnProperty("speakers")&&a.speakers!==false&&a.speakers.length>r.speaker&&O(a.speakers.slice(r.speaker),"speaker");a.hasOwnProperty("speakerTimeline")&&a.speakerTimeline!==false&&a.speakerTimeline.length>0&&N(a.speakerTimeline,"speaker")}l.breaks&&a.hasOwnProperty("eventBreaks")&&a.eventBreaks!==false&&a.eventBreaks.length>
0&&U(a.eventBreaks)},jumpToTopic:function(a){a=Q.topic[a];a!==undefined?A(a):i(h.no_timestamp,true)}};return d}(jQuery);